name: taco-rewards-bot

plugins:
  - name: solidity
  # - name: ape-etherscan

dependencies:
  - name: nucypher-contracts
    github: nucypher/nucypher-contracts
    ref: main
    config_override:
      solidity:
        version: 0.8.23
        evm_version: paris
        import_remapping:
          - "@openzeppelin/contracts=openzeppelin/v5.0.0"
          - "@openzeppelin-upgradeable/contracts=openzeppelin-upgradeable/v5.0.0"
          - "@fx-portal/contracts=fx-portal/v1.0.5"
          - "@threshold/contracts=threshold/v1.2.1"
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.0
